import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

import { labelsEn } from "@/app/data/labels";

import logo from "@/app/assets/VA.png";
import NavBar from "@/app/Components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-12 flex justify-between text-cyan-950 items-center p-4 px-24 shadow-xl bg-cyan-100">
          <h1 className="flex gap-2 items-center">
            <Image
              src={logo}
              alt="icon ViewArt"
              className="w-[50px] h-[25px]"
            />
            <Link href="/">{labelsEn.artworkTitleNav}</Link>
          </h1>
          <NavBar></NavBar>
        </header>
        {children}
      </body>
    </html>
  );
}
