export const dataList = [
  {
    nome: "Leonardo",
    cognome: "da Vinci",
    anno: "1452",
    corrente: "Rinascimento",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Michelangelo",
    cognome: "Buonarroti",
    anno: "1475",
    corrente: "Rinascimento",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Raphael",
    cognome: "Sanzio",
    anno: "1483",
    corrente: "Rinascimento",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Pablo",
    cognome: "Picasso",
    anno: "1881",
    corrente: "Cubismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Georges",
    cognome: "Braque",
    anno: "1882",
    corrente: "Cubismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Vincent",
    cognome: "van Gogh",
    anno: "1853",
    corrente: "Post-impressionismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Paul",
    cognome: "Gauguin",
    anno: "1848",
    corrente: "Post-impressionismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Salvador",
    cognome: "Dalí",
    anno: "1904",
    corrente: "Surrealismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "Joan",
    cognome: "Miró",
    anno: "1893",
    corrente: "Surrealismo",
    id: self.crypto.randomUUID(),
  },
  {
    nome: "René",
    cognome: "Magritte",
    anno: "1898",
    corrente: "Surrealismo",
    id: self.crypto.randomUUID(),
  },
];
